services:
  nginx:
    image: nginx:stable
    container_name: ils_nginx
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ils_php
    volumes:
      - ./src:/var/www/html
      - ./vendor:/var/www/html/vendor  # Fixed: Mount vendor inside html directory
    env_file: .env
    environment:
      TZ: ${TZ}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      ADMIN_CODE: ${ADMIN_CODE}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_ENCRYPTION: ${SMTP_ENCRYPTION}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      SMS_API_URL: ${SMS_API_URL}
      SMS_API_KEY: ${SMS_API_KEY}
      SMS_SENDER_ID: ${SMS_SENDER_ID}
    restart: always

  db:
    image: mysql:8.0
    container_name: ils_db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/library.sql:/docker-entrypoint-initdb.d/library.sql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ils_phpmyadmin
    restart: always
    env_file: .env
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db

volumes:
  db_data:
