services:
  nginx:
    image: nginx:stable
    container_name: ils_nginx
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always

  php:
    image: integrated-library-system-php:latest
    container_name: ils_php
    volumes:
      - ./src:/var/www/html
    env_file: .env
    environment:
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db

volumes:
  db_data:
